spring.application.naame: kotlin
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: stg

---
spring.config.activate.on-profile: live